name: Deploy MediSync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Build Backend
      run: |
        cd backend
        dotnet build --configuration Release
    
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'medisyncfunct'
        slot-name: 'production'
        package: './backend/bin/Release/net6.0'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        echo "REACT_APP_API_BASE_URL=https://medisyncfunct.azurewebsites.net/api" > .env.production
        npm run build
    
    - name: Deploy Frontend to Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name medisync9e8a --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_KEY }} --source frontend/build/ --destination '$web'